// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	executor "doggos/executor"

	mock "github.com/stretchr/testify/mock"
)

// RequestFactory is an autogenerated mock type for the RequestFactory type
type RequestFactory struct {
	mock.Mock
}

// Build provides a mock function with given fields: page, size, breedID
func (_m *RequestFactory) Build(page int, size int, breedID string) (*executor.Request, error) {
	ret := _m.Called(page, size, breedID)

	var r0 *executor.Request
	if rf, ok := ret.Get(0).(func(int, int, string) *executor.Request); ok {
		r0 = rf(page, size, breedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*executor.Request)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int, string) error); ok {
		r1 = rf(page, size, breedID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
