// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domainmodel "doggos/domain/model"

	mock "github.com/stretchr/testify/mock"

	model "doggos/repo/model"
)

// DoggosMapper is an autogenerated mock type for the DoggosMapper type
type DoggosMapper struct {
	mock.Mock
}

// Map provides a mock function with given fields: doggos
func (_m *DoggosMapper) Map(doggos []model.DoggoDto) []domainmodel.Doggo {
	ret := _m.Called(doggos)

	var r0 []domainmodel.Doggo
	if rf, ok := ret.Get(0).(func([]model.DoggoDto) []domainmodel.Doggo); ok {
		r0 = rf(doggos)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domainmodel.Doggo)
		}
	}

	return r0
}
